version: "3.9"

services:
  app:
    build: .
    container_name: chat_bot
    env_file:
      - .env
    restart: unless-stopped

    # чтобы контейнер видел хост
    extra_hosts:
      - "host.docker.internal:host-gateway"

    # если приложение слушает порт — раскомментируй
    # ports:
    #   - "8000:8000"

    # если нужны файлы/кеши/логи
    # volumes:
    #   - ./assets:/app/assets
